## M45 cross-language pilot fixture (REVERSE direction) — a C++
## binary that calls into a D static library, declared together in a
## single workspace ``repro.nim``. Closes the loop opened by the
## sibling ``mixed/d-uses-cpp-lib/`` fixture: that one routes D -> C;
## this one routes C++ -> D.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract in the REVERSE direction:
##
##   * TWO packages in a single ``repro.nim``: ``daddlib`` (a D
##     static library, ``uses: d``) and ``cppapp`` (a C++ executable,
##     ``uses: gcc``).
##   * ``depends_on cppapp: daddlib`` — the C++ binary's link picks
##     up the D archive. The cross-language dep cannot be detected by
##     the scanner (the C++ scanner only sees a same-package include
##     of ``cppapp/d_addlib.h``); the manual edge is the source of
##     truth.
##
## The d-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names a D toolchain token and no ``dub.json`` / ``dub.sdl`` is
## present. It then:
##   * Emits the D library via ``ldmd2 -lib`` landing at
##     ``.repro/build/daddlib/libdaddlib.a`` — the canonical archive
##     schema shared with c-cpp-direct, Rust's staticlib path,
##     Fortran's archive path, and Zig's static archive.
##   * Emits per-source ``g++ -c`` actions for ``cppapp/src/*.cpp``
##     plus a terminal ``g++ -o cppapp.exe`` link action. The link
##     argv carries ``libdaddlib.a`` as a trailing positional.
##
##     The M45 honest-scope cut limits the reverse fixture to
##     ``extern (C)`` entry points + ``core.stdc.*`` (no ``import
##     std.*`` / no GC) so the gcc driver resolves all references
##     against the D archive itself without external runtime libs —
##     same property Zig's M44 reverse fixture relies on. Full
##     ``phobos2``/``druntime`` linking + ``Initialize_runtime`` /
##     ``Terminate_runtime`` bracket calls are deferred to a future
##     milestone.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     daddlib/src/lib.d                       # D source (Layout B)
##     cppapp/src/main.cpp                     # C++ source (Layout B)
##     cppapp/include/cppapp/d_addlib.h        # hand-written C header
##
## NOTE on header authorship: the user writes
## ``cppapp/include/cppapp/d_addlib.h`` BY HAND. Auto-generating C
## headers from D sources is out of scope for this milestone.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package daddlib:
  uses:
    "d"

  library daddlib

package cppapp:
  uses:
    "gcc >=11"

  executable cppapp:
    discard

# Manual dep edge: the C++ source's ``#include "cppapp/d_addlib.h"``
# is a SAME-PACKAGE include (the header lives under cppapp/include/),
# so the C/C++ scanner produces no cross-package edge. The
# cross-language dep ``cppapp -> daddlib`` is hand-authored here.
depends_on cppapp: daddlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
