## M36 cross-language pilot fixture (FORWARD direction) — a Go binary
## that calls into a C static library via cgo, declared together in a
## single workspace ``repro.nim``. The Go convention's M36 cgo path is
## the cross-language sibling of the Rust/Nim → C forward-direction
## pilots (mixed/rust-uses-cpp-lib + mixed/nim-uses-cpp-lib).
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-
## language contract for cgo:
##
##   * TWO packages in a single ``repro.nim``: ``mathlib`` (a C static
##     library, ``uses: gcc``) and ``calc`` (a Go executable,
##     ``uses: go``).
##   * ``depends_on calc: mathlib`` — the Go binary's cgo build picks
##     up the C archive. The Go source's ``import "C"`` block carries
##     the ``#include "mathlib/add.h"`` directive; the convention
##     wires the upstream archive onto the ``go build`` invocation via
##     ``-ldflags '-extldflags=-L<dir> -l<libname>'``.
##
## The go-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names ``go`` and no ``go.mod`` / ``go.work`` is present. It then:
##   * Emits per-source ``gcc -c`` actions for ``mathlib/src/*.c`` plus
##     a terminal ``ar rcs libmathlib.a`` archive action, landing the
##     archive at ``.repro/build/mathlib/libmathlib.a``.
##   * Switches the Go binary's build from ``go tool compile`` +
##     ``go tool link`` (the M31 pure-Go fast path) to ``go build``
##     because cgo requires Go's full build pipeline. The action's
##     argv carries ``-ldflags=-extldflags=-L<dir> -l<libname>`` so
##     the cgo external linker picks up the C archive. ``CGO_ENABLED``
##     defaults to 1 in modern Go toolchains and ``CC`` resolves to
##     ``gcc`` on the host PATH.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     mathlib/src/add.c                     # C source (Layout B)
##     mathlib/include/mathlib/add.h         # public header
##     calc/main.go                          # Go source with cgo block
##
## NOTE on the cgo runtime initialiser: unlike Nim's ``NimMain()``, a
## Go executable using cgo to call C does not need an explicit
## initialiser — the Go runtime's startup wires everything up before
## ``main()`` runs. The cgo wrappers (``_cgo_*``) generated at build
## time handle the cross-language ABI shim.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlib:
  uses:
    "gcc >=11"

  library mathlib

package calc:
  uses:
    "go"

  executable calc:
    discard

# Manual dep edge: the Go source's ``import "C"`` block carries a
# ``#include "mathlib/add.h"`` directive but no upstream-package
# reference; the Go import scanner cannot infer the cross-language
# link from that evidence. Hand-authored here today; once a scanner
# extension learns to fold cgo's ``#include`` directives into the dep
# graph, this edge moves into ``repro.scanned-deps.nim`` and the
# include below picks it up.
depends_on calc: mathlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# This file is empty today (the scanner cannot see the cross-language
# edge above) but the ``include`` is kept so the regeneration pipeline
# stays operative for future scanner extensions.
include "repro.scanned-deps.nim"
