## M58 Mode 3 Ada pilot fixture — pure Ada ``binary-with-library``.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" shape for
## Ada per the M58 section of
## ``reprobuild-specs/Provisioning-And-Languages-Expansion.milestones.org``
## (the minimal subset the M58 ``ada-direct`` convention implements):
##
##   * NO ``*.gpr`` at the workspace root (Mode 2 ``gprbuild`` delegation
##     is deferred per the M58 honest-scope cut).
##   * Two packages declared in a single ``repro.nim``:
##     ``adalibPkg`` ships a static library ``adalib`` exposing a
##     ``pragma Export (C)``-marked function; ``adacalcPkg`` ships an
##     executable ``adacalc`` whose source ``with``-clauses the library
##     and calls the exported function.
##   * Per-package layout under the workspace root (Layout B):
##       adalib/src/lib.adb     + adalib/src/lib.ads
##       adacalc/src/main.adb
##
## The ``ada-direct`` convention turns the
## ``depends_on adacalcPkg: adalibPkg`` edge into real action-graph
## edges: ``adacalc``'s ``gnatmake -O2 -o adacalc.exe main.adb``
## action declares ``adalib``'s ``libadalib.a`` static archive as an
## explicit input + trailing ``-largs <archive>`` (gnatmake linker
## pass-through), plus depends on the ``adalib`` package's ``ar rcs``
## archive action. gnatmake's underlying linker resolves the
## cross-package symbol at link time.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package adalibPkg:
  uses:
    "gnatmake"

  library adalib

package adacalcPkg:
  uses:
    "gnatmake"

  executable adacalc:
    discard

# Manual dep edge: the M58 convention does not ship an Ada ``with``
# clause scanner so cross-package edges are hand-authored. Once a
# future milestone lands the scanner this edge can move into
# ``repro.scanned-deps.nim``.
depends_on adacalcPkg: adalibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# Empty today (no Ada ``with`` scanner) but the include is kept so the
# regeneration pipeline stays operative for future scanner extensions.
include "repro.scanned-deps.nim"
