## M35 cross-language Mode 3 pilot (REVERSE direction) — a Rust binary
## that calls into a Nim static library, declared together in a single
## workspace ``repro.nim``. Closes the loop opened by the sibling
## ``mixed/nim-uses-rust-lib/`` fixture: that one routes Nim -> Rust;
## this one routes Rust -> Nim.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract IN THE REVERSE DIRECTION (Rust consumes a Nim archive):
##
##   * TWO packages in a single ``repro.nim``: ``nimaddlib`` (a Nim
##     static library, ``uses: nim``) and ``rustapp`` (a Rust executable,
##     ``uses: rust``).
##   * ``depends_on rustapp: nimaddlib`` — the Rust binary links against
##     the Nim archive. The cross-language dep cannot be detected by the
##     scanner (the Rust ``use`` scanner only sees intra-Rust ``use``
##     declarations); the manual edge is the source of truth.
##
## The Nim convention takes ownership of the WHOLE workspace because
## it's registered first AND ``nimaddlib``'s ``uses:`` block names
## ``nim``. It then:
##   * Emits the Nim archive for ``nimaddlib`` with ``--noMain`` so the
##     archive's ``main`` symbol does NOT collide with the Rust binary's
##     own entry point at link time. The archive contains both the
##     user-exported ``nimAdd`` symbol AND Nim's runtime-init ``NimMain``
##     entry point (the Rust binary calls ``NimMain()`` once before any
##     Nim function). The ``--noMain`` flag is driven by the
##     ``cConsumable`` toggle that the convention derives from the
##     ``depends_on rustapp: nimaddlib`` edge.
##   * Emits a single ``rustc --crate-type=bin`` action for ``rustapp``.
##     The link argv carries ``-L native=<dir>`` + ``-l static=nimaddlib``
##     plus the Nim runtime libs (``-lm`` on POSIX; nothing on Windows
##     MinGW — rustc picks up the C runtime via msvcrt implicitly via
##     its default link line). Build sequencing strictly orders archive
##     before link.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     nimaddlib/src/nimaddlib.nim            # Nim source (Layout B)
##     rustapp/src/main.rs                    # Rust source (Layout B)
##
## NOTE on ``NimMain()``: the Rust source MUST call ``NimMain()`` once
## at startup before invoking any other Nim function. The convention
## does NOT auto-insert this call — the user writes it explicitly in
## their Rust code via an ``extern "C"`` declaration. This is the
## documented Nim FFI contract (see https://nim-lang.org/docs/nimc.html
## #dll-mode "Lib mode"); the convention simply ensures the symbol is
## exported from the archive (via ``--noMain``).
##
## NOTE on extern decls: the Rust source declares ``extern "C"``
## blocks for ``nimAdd`` and ``NimMain`` directly — no separate C
## header file is needed (Rust's ``extern "C"`` syntax already declares
## the ABI inline). This is a small win over the C++ case where the
## user typically writes a separate ``nim_addlib.h``.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package nimaddlib:
  uses:
    "nim >=2.2 <3.0"

  library nimaddlib

package rustapp:
  uses:
    "rust"

  executable rustapp:
    discard

# Manual dep edge: the Rust source's ``extern "C" { fn nimAdd(...); }``
# block references the Nim symbol by name; the Rust use-scanner does
# not walk extern blocks. The cross-language dep ``rustapp -> nimaddlib``
# is hand-authored here today.
depends_on rustapp: nimaddlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
