## M34 cross-language pilot fixture — a Rust binary that calls into a
## C static library, declared together in a single workspace
## ``repro.nim``. Mirrors the Phase 2 cross-language schema for the
## Rust↔C/C++ direction. The forward direction (Rust → C) is one of two
## directions M34 ships; see the sibling ``mixed/cpp-uses-rust-lib/``
## fixture for the reverse case (C++ → Rust).
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract:
##
##   * TWO packages in a single ``repro.nim``: ``mathlib`` (a C static
##     library, ``uses: gcc``) and ``calc`` (a Rust executable,
##     ``uses: rust``).
##   * ``depends_on calc: mathlib`` — the Rust binary's link picks up
##     the C archive. The cross-language dep cannot be auto-detected by
##     the Rust scanner (the scanner only sees ``extern "C" { fn add
##     ... }`` which has no upstream-package reference); the manual
##     edge is the source of truth.
##
## The rust-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names ``rust`` and no ``Cargo.toml`` is present. It then:
##   * Emits per-source ``gcc -c`` actions for ``mathlib/src/*.c`` plus
##     a terminal ``ar rcs libmathlib.a`` archive action, landing the
##     archive at ``.repro/build/mathlib/libmathlib.a``.
##   * Threads ``-L native=<.repro/build/mathlib>`` ``-l static=mathlib``
##     onto the Rust binary's ``rustc`` link argv, plus the archive's
##     path on ``inputs`` + the archive action's id on ``deps``. The
##     engine sequences the archive build strictly before the rustc
##     link, and the linked executable resolves ``add`` against the C
##     archive.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     mathlib/src/add.c                     # C source (Layout B)
##     mathlib/include/mathlib/add.h         # public header
##     calc/src/main.rs                      # Rust source (Layout B)
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlib:
  uses:
    "gcc >=11"

  library mathlib

package calc:
  uses:
    "rust"

  executable calc:
    discard

# Manual dep edge: the Rust source's ``extern "C" { fn add(...) }``
# block names the symbol ``add`` but not the upstream package; the
# Rust import scanner cannot infer the cross-language link from that
# evidence. Hand-authored here today; once a scanner extension learns
# to fold ``extern "C"``-block declarations into the dep graph, this
# edge moves into ``repro.scanned-deps.nim`` and the include below
# picks it up.
depends_on calc: mathlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# This file is empty today (the scanner cannot see the cross-language
# edge above) but the ``include`` is kept so the regeneration pipeline
# stays operative for future scanner extensions.
include "repro.scanned-deps.nim"
