## M45 Mode 3 D pilot fixture — pure D ``binary-with-library``.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" shape for
## D per the M45 section of
## ``reprobuild-specs/Mode3-Language-Expansion.milestones.org`` (the
## minimal subset the M45 ``d-direct`` convention implements):
##
##   * NO ``dub.json`` / ``dub.sdl`` at the workspace root (Mode 2
##     ``dub build`` delegation is deferred per the M45 honest-scope
##     cut).
##   * Two packages declared in a single ``repro.nim``:
##     ``dlibPkg`` ships a static library ``dlib`` exposing an
##     ``extern (C)``-marked function; ``dcalcPkg`` ships an
##     executable ``dcalc`` whose source links the library archive.
##   * Per-package layout under the workspace root (Layout B):
##       dlib/src/lib.d
##       dcalc/src/main.d
##
## The ``d-direct`` convention turns the
## ``depends_on dcalcPkg: dlibPkg`` edge into real action-graph
## edges: ``dcalc``'s ``ldmd2 -of=...`` link action declares
## ``dlib``'s ``libdlib.a`` static archive as an explicit input AND
## as ``-L=<archive>`` (linker pass-through) on the link argv, plus
## depends on the ``dlib`` package's ``ldmd2 -lib`` action id. The
## D driver's underlying linker resolves the cross-package symbol at
## link time.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package dlibPkg:
  uses:
    "d"

  library dlib

package dcalcPkg:
  uses:
    "d"

  executable dcalc:
    discard

# Manual dep edge: the M45 convention does not ship a D ``import`` /
# ``extern`` scanner so cross-package edges are hand-authored. Once a
# future milestone lands the scanner this edge can move into
# ``repro.scanned-deps.nim``.
depends_on dcalcPkg: dlibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# Empty today (no D import scanner) but the include is kept so the
# regeneration pipeline stays operative for future scanner extensions.
include "repro.scanned-deps.nim"
