## Mode 3 Rust pilot fixture — `binary-with-library`.
##
## Demonstrates the three-mode convention system's Mode 3 surface for
## Rust (curated `repro.nim` + auto-scanned dep graph) per
## `reprobuild-specs/Three-Mode-Convention-System.md` and the M30
## section of `reprobuild-specs/Mode3-Language-Expansion.milestones.org`:
##
##   * NO `Cargo.toml` at all — Mode 3 Rust is in-workspace only.
##   * Two packages declared in a single `repro.nim`:
##     `mathlibPkg` ships a static library `mathlib`; `calcPkg` ships
##     an executable `calc` whose source `use`s the library crate.
##   * Per-package layout under the workspace root (Layout B in
##     `repro_core/rust_dep_scanner`):
##       mathlib/src/lib.rs
##       calc/src/main.rs
##   * The scanner reads `repro.scanned-deps.nim` (machine-authored
##     via `repro deps refresh`) at the bottom of this file and emits
##     the `calcPkg -> mathlibPkg` edge by recognising the
##     `use mathlib::add;` line in `calc/src/main.rs`.
##
## The Mode 3 Rust convention (`rust-direct`) turns the
## `depends_on calcPkg: mathlibPkg` edge into real action-graph edges:
## `calc`'s `rustc -o calc[.exe]` link action declares `mathlib`'s
## `libmathlib.rlib` as both an explicit input AND a trailing
## `--extern mathlib=<rlib>` flag, and depends on the `mathlib`
## package's `rustc --crate-type rlib` action id. M30 emits rlib (not
## staticlib) because Rust-to-Rust `use upstream::...` requires the
## metadata only rlib carries; M34 will add a sibling staticlib
## action for cross-language C/C++ consumption.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlibPkg:
  uses:
    "rust"

  library mathlib

package calcPkg:
  uses:
    "rust"

  executable calc:
    discard

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# The scanner emits the `calcPkg -> mathlibPkg` edge (proved by
# `calc/src/main.rs`'s `use mathlib::add;` line).
include "repro.scanned-deps.nim"
