## M37 cross-language pilot fixture (FORWARD direction) — a Fortran
## binary that calls into a C static library, declared together in a
## single workspace ``repro.nim``. Mirrors the M34 ``mixed/rust-uses-cpp-lib``
## shape but on the Fortran ↔ C axis.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract:
##
##   * TWO packages in a single ``repro.nim``: ``mathlib`` (a C static
##     library, ``uses: gcc``) and ``fortcalc`` (a Fortran executable,
##     ``uses: gfortran``).
##   * ``depends_on fortcalc: mathlib`` — the Fortran binary's link
##     picks up the C archive. The cross-language dep cannot be auto-
##     detected by the Fortran scanner (M37 doesn't ship one); the
##     manual edge is the source of truth.
##
## The ``fortran-direct`` convention takes ownership of the WHOLE
## workspace because ``c-cpp-direct``'s recognize defers when ``uses:``
## anywhere names ``gfortran``/``fortran``. It then:
##   * Emits per-source ``gcc -c`` actions for ``mathlib/src/*.c`` plus
##     a terminal ``ar rcs libmathlib.a`` archive action, landing the
##     archive at ``.repro/build/mathlib/libmathlib.a``.
##   * Emits per-source ``gfortran -c`` actions for ``fortcalc/src/*.f90``
##     plus a terminal ``gfortran -o fortcalc[.exe]`` link action that
##     threads the C archive as a trailing positional. The engine
##     sequences the archive build strictly before the gfortran link,
##     and the linked executable resolves the C ``c_add`` symbol against
##     the archive.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     mathlib/src/c_add.c                   # C source (Layout B)
##     mathlib/include/mathlib/c_add.h       # public header
##     fortcalc/src/main.f90                 # Fortran source (Layout B)
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path

import repro_project_dsl

package mathlib:
  uses:
    "gcc >=11"

  library mathlib

package fortcalc:
  uses:
    "gfortran"

  executable fortcalc:
    discard

# Manual dep edge: the Fortran source's ``interface`` block names the
# symbol ``c_add`` but not the upstream package; the M37 convention
# does not ship a cross-language scanner. Hand-authored here today.
depends_on fortcalc: mathlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
