## M44 cross-language pilot fixture (FORWARD direction) — a Zig binary
## that calls into a C static library, declared together in a single
## workspace ``repro.nim``. Mirrors the Phase 4 cross-language schema
## for the Zig↔C/C++ direction. The forward direction (Zig → C) is one
## of two directions M44 ships; see the sibling
## ``mixed/cpp-uses-zig-lib/`` fixture for the reverse case (C++ → Zig).
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract:
##
##   * TWO packages in a single ``repro.nim``: ``mathlib`` (a C static
##     library, ``uses: gcc``) and ``zigcalc`` (a Zig executable,
##     ``uses: zig``).
##   * ``depends_on zigcalc: mathlib`` — the Zig binary's link picks up
##     the C archive. The cross-language dep cannot be auto-detected by
##     a Zig source scanner (the scanner would see ``extern fn
##     c_add(...)`` which carries no upstream-package reference); the
##     manual edge is the source of truth.
##
## The zig-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names ``zig`` and no ``build.zig`` is present. It then:
##   * Emits per-source ``gcc -c`` actions for ``mathlib/src/*.c``
##     plus a terminal ``ar rcs libmathlib.a`` archive action, landing
##     the archive at ``.repro/build/mathlib/libmathlib.a``.
##   * Threads the archive as a trailing positional on the
##     ``zig build-exe`` argv plus the archive's parent dir as ``-L
##     <dir>`` so Zig's underlying linker resolves ``c_add`` at link
##     time.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     mathlib/src/add.c                     # C source (Layout B)
##     mathlib/include/mathlib/add.h         # public header
##     zigcalc/src/main.zig                  # Zig source (Layout B)
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlib:
  uses:
    "gcc >=11"

  library mathlib

package zigcalc:
  uses:
    "zig"

  executable zigcalc:
    discard

# Manual dep edge: the Zig source's ``extern fn c_add(...)`` declares
# the symbol but not the upstream package; the Zig scanner cannot
# infer the cross-language link from that evidence. Hand-authored
# here today; once a scanner extension learns to fold ``extern fn``
# declarations into the dep graph, this edge moves into
# ``repro.scanned-deps.nim``.
depends_on zigcalc: mathlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
