## M37 cross-language pilot fixture (REVERSE direction) — a C++ binary
## that calls into a Fortran static library, declared together in a
## single workspace ``repro.nim``. Mirrors the M34 ``mixed/cpp-uses-rust-lib``
## shape but on the C++ ↔ Fortran axis.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract in the REVERSE direction:
##
##   * TWO packages in a single ``repro.nim``: ``fortaddlib`` (a Fortran
##     static library, ``uses: gfortran``) and ``cppapp`` (a C++
##     executable, ``uses: gcc``).
##   * ``depends_on cppapp: fortaddlib`` — the C++ binary's link picks
##     up the Fortran archive. The cross-language dep cannot be
##     detected by the scanner (the C++ scanner only sees a same-
##     package include of ``cppapp/fortran_addlib.h``); the manual
##     edge is the source of truth.
##
## The ``fortran-direct`` convention takes ownership of the WHOLE
## workspace because ``c-cpp-direct``'s recognize defers when ``uses:``
## anywhere names ``gfortran``. It then:
##   * Emits per-source ``gfortran -c`` actions for ``fortaddlib/src/*.f90``
##     plus a terminal ``ar rcs libfortaddlib.a`` archive action. The
##     archive lands at ``.repro/build/fortaddlib/libfortaddlib.a`` —
##     the canonical archive schema shared with c-cpp-direct and the
##     other Mode 3 conventions.
##   * Emits per-source ``g++ -c`` actions for ``cppapp/src/*.cpp`` plus
##     a terminal ``g++ -o cppapp.exe`` link action. The link argv
##     carries ``libfortaddlib.a`` as a trailing positional plus the
##     platform-specific Fortran runtime libs (``-lgfortran -lquadmath
##     -lm``, plus ``-lpthread`` on POSIX). The archive's path is added
##     to ``inputs`` + the archive action's id is added to ``deps``.
##     Build sequencing strictly orders archive before link.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     fortaddlib/src/lib.f90                  # Fortran source (Layout B)
##     cppapp/src/main.cpp                     # C++ source (Layout B)
##     cppapp/include/cppapp/fortran_addlib.h  # hand-written C header
##
## NOTE on header authorship: the user writes
## ``cppapp/include/cppapp/fortran_addlib.h`` BY HAND. Auto-generating C
## headers from Fortran sources is out of scope for this milestone.
##
## NOTE on Fortran runtime: the C++ binary's link argv carries
## ``-lgfortran -lquadmath -lm`` so the archive's compiled references
## to the Fortran runtime (intrinsics like ``print``-driven I/O setup,
## though this fixture's ``fortran_add`` doesn't touch any of them)
## resolve. We thread the runtime libs unconditionally — the linker
## drops them when nothing in the archive references them.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path

import repro_project_dsl

package fortaddlib:
  uses:
    "gfortran"

  library fortaddlib

package cppapp:
  uses:
    "gcc >=11"

  executable cppapp:
    discard

# Manual dep edge: the C++ source's ``#include "cppapp/fortran_addlib.h"``
# is a SAME-PACKAGE include, so the C/C++ scanner produces no cross-
# package edge. The cross-language dep is hand-authored.
depends_on cppapp: fortaddlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
