## M37 Mode 3 Fortran pilot fixture — pure Fortran ``binary-with-library``.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" shape for
## Fortran per ``Language-Conventions/Fortran.md`` (the minimal subset
## the M37 ``fortran-direct`` convention implements):
##
##   * NO ``fpm.toml`` (fpm-Mode-2 delegation is deferred).
##   * Two packages declared in a single ``repro.nim``:
##     ``fortlibPkg`` ships a static library ``fortlib`` exposing a
##     ``bind(C)`` function; ``fortcalcPkg`` ships an executable
##     ``fortcalc`` whose source calls into the library.
##   * Per-package layout under the workspace root (Layout B):
##       fortlib/src/lib.f90
##       fortcalc/src/main.f90
##
## The ``fortran-direct`` convention turns the
## ``depends_on fortcalcPkg: fortlibPkg`` edge into real action-graph
## edges: ``fortcalc``'s ``gfortran -o fortcalc[.exe]`` link action
## declares ``fortlib``'s ``libfortlib.a`` static archive as an
## explicit input AND as a trailing positional on the link argv, plus
## depends on the ``fortlib`` package's ``ar rcs libfortlib.a`` action
## id. ``gfortran``'s link driver pulls in libgfortran + the rest of
## the Fortran runtime automatically.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package fortlibPkg:
  uses:
    "gfortran"

  library fortlib

package fortcalcPkg:
  uses:
    "gfortran"

  executable fortcalc:
    discard

# Manual dep edge: the M37 convention does not ship a Fortran ``USE`` /
# ``CALL`` scanner so cross-package edges are hand-authored. Once a
# future milestone lands the scanner this edge can move into
# ``repro.scanned-deps.nim``.
depends_on fortcalcPkg: fortlibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# Empty today (no Fortran USE/MODULE scanner) but the include is kept
# so the regeneration pipeline stays operative for future scanner
# extensions.
include "repro.scanned-deps.nim"
