## M35 cross-language Mode 3 pilot (FORWARD direction) — a Nim binary
## that calls into a Rust static library, declared together in a single
## workspace ``repro.nim``. The Rust-side reverse of this fixture is
## ``mixed/rust-uses-nim-lib/``; the C/C++ analogue is
## ``mixed/nim-uses-cpp-lib/``.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract in the FORWARD direction (Nim consumes a non-Nim archive):
##
##   * TWO packages in a single ``repro.nim``: ``addlib`` (a Rust static
##     library, ``uses: rust``) and ``nimapp`` (a Nim executable,
##     ``uses: nim``).
##   * ``depends_on nimapp: addlib`` — the Nim binary's link picks up
##     the Rust archive. The cross-language dep cannot be detected by
##     the scanner (the Nim import-scanner only extracts ``import foo``
##     lines); the manual edge is the source of truth.
##
## The Nim convention takes ownership of the WHOLE workspace because
## it's registered first AND ``nimapp``'s ``uses:`` block names ``nim``.
## It then:
##   * Emits the Rust library as ``rustc --crate-type=staticlib`` with
##     ``-C panic=abort`` so the no_std archive (the realistic FFI
##     pattern) links cleanly. Output lands at
##     ``.repro/build/addlib/libaddlib.a`` — canonical archive schema
##     shared with c-cpp-direct + the Nim convention's own static
##     library output + rust_direct's reverse staticlib emit.
##   * Emits the Nim three-phase pipeline for ``nimapp``. Phase 3's gcc
##     link picks up ``libaddlib.a`` as a trailing positional plus the
##     platform-specific Rust runtime libs (Windows MinGW: ``-lws2_32
##     -luserenv -ladvapi32 -lbcrypt -lntdll``; POSIX: ``-lpthread
##     -ldl -lm``). The archive's path is added to ``inputs`` + the
##     archive action's id is added to ``deps``. Build sequencing
##     strictly orders the rustc staticlib emit before the Nim link.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     addlib/src/lib.rs                      # Rust source (Layout B)
##     src/nimapp.nim                         # Nim source (Layout A)
##
## NOTE on Rust runtime initialisation: unlike Nim (which requires a
## ``NimMain()`` call before any Nim function), a Rust ``extern "C"``
## function with ``#[no_mangle]`` is directly callable from Nim — the
## Rust runtime initialiser (if any) is wired up automatically by the
## rustc static archive's link metadata. The Nim source can call
## ``rust_add`` directly without an explicit initialiser.
##
## NOTE on header authorship: Nim's ``{.importc, cdecl.}`` declaration
## is the only ceremony required to call into Rust — no hand-written
## C header is needed (Nim's foreign-function pragmas already declare
## the ABI inline). This is a small win over the C++ case where the
## user writes a separate ``rust_addlib.h``.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package addlib:
  uses:
    "rust"

  library addlib

package nimapp:
  uses:
    "nim >=2.2 <3.0"

  executable nimapp:
    discard

# Manual dep edge: the Nim source's ``{.importc, cdecl.}`` declaration
# references the Rust symbol by name; the Nim import-scanner does not
# walk pragmas. The cross-language dep ``nimapp -> addlib`` is
# hand-authored here today.
depends_on nimapp: addlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
