## M58 cross-language pilot fixture (FORWARD direction) — an Ada
## binary that calls into a C static library, declared together in a
## single workspace ``repro.nim``. Mirrors the Phase 4 cross-language
## schema for the Ada↔C/C++ direction. The forward direction
## (Ada → C) is one of two directions M58 ships; see the sibling
## ``mixed/cpp-uses-ada-lib/`` fixture for the reverse case (C++ → Ada).
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3"
## cross-language contract:
##
##   * TWO packages in a single ``repro.nim``: ``mathlib`` (a C static
##     library, ``uses: gcc``) and ``adacalc`` (an Ada executable,
##     ``uses: gnatmake``).
##   * ``depends_on adacalcPkg: mathlibPkg`` — the Ada binary's link
##     picks up the C archive. The cross-language dep cannot be
##     auto-detected by an Ada source scanner (the scanner would see
##     ``pragma Import (C, C_Add, "c_add")`` which carries no
##     upstream-package reference); the manual edge is the source of
##     truth.
##
## The ada-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names an Ada toolchain token and no ``*.gpr`` is present. It then:
##   * Emits per-source ``gcc -c`` actions for ``mathlib/src/*.c``
##     plus a terminal ``ar rcs libmathlib.a`` archive action, landing
##     the archive at ``.repro/build/mathlib/libmathlib.a``.
##   * Threads the archive on the ``gnatmake`` argv AFTER the
##     ``-largs`` separator (linker pass-through) so gnatmake's
##     underlying linker resolves ``c_add`` at link time.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     mathlib/src/add.c                     # C source (Layout B)
##     mathlib/include/mathlib/add.h         # public header
##     adacalc/src/main.adb                  # Ada source (Layout B)
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>

import repro_project_dsl

package mathlibPkg:
  uses:
    "gcc >=11"

  library mathlib

package adacalcPkg:
  uses:
    "gnatmake"

  executable adacalc:
    discard

# Manual dep edge: the Ada source's ``pragma Import (C, ...)`` declares
# the symbol but not the upstream package; the Ada scanner cannot
# infer the cross-language link from that evidence. Hand-authored
# here today; once a scanner extension learns to fold ``pragma Import``
# declarations into the dep graph, this edge moves into
# ``repro.scanned-deps.nim``.
depends_on adacalcPkg: mathlibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
