## Mode 3 Go pilot fixture — `binary-with-library`.
##
## Demonstrates the three-mode convention system's Mode 3 surface for
## Go (curated `repro.nim` + auto-scanned dep graph) per
## `reprobuild-specs/Three-Mode-Convention-System.md` and the M31
## section of `reprobuild-specs/Mode3-Language-Expansion.milestones.org`:
##
##   * NO `go.mod` at all — Mode 3 Go is in-workspace only.
##   * Two packages declared in a single `repro.nim`:
##     `mathlibPkg` ships a static library `mathlib`; `calcPkg` ships
##     an executable `calc` whose source `import`s the library package.
##   * Per-package layout under the workspace root (Layout B in
##     `repro_core/go_dep_scanner`):
##       mathlib/add.go
##       calc/main.go
##   * The scanner reads `repro.scanned-deps.nim` (machine-authored
##     via `repro deps refresh`) at the bottom of this file and emits
##     the `calcPkg -> mathlibPkg` edge by recognising the
##     `import "mathlib"` line in `calc/main.go`.
##
## The Mode 3 Go convention (`go-direct`) turns the
## `depends_on calcPkg: mathlibPkg` edge into real action-graph edges:
## `calc`'s `go tool compile` action declares `mathlib`'s
## `mathlib.a` archive in its `importcfg`, and `calc`'s `go tool link`
## action references the same archive in `importcfg.link`. The link
## action depends on the `mathlib` package's `go tool compile` action
## id so the build order is enforced.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlibPkg:
  uses:
    "go"

  library mathlib

package calcPkg:
  uses:
    "go"

  executable calc:
    discard

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# The scanner emits the `calcPkg -> mathlibPkg` edge (proved by
# `calc/main.go`'s `import "mathlib"` line).
include "repro.scanned-deps.nim"
