## Mode 3 cross-language pilot fixture — a C++ binary that calls into a
## Nim static library, declared together in a single workspace
## ``repro.nim``. Closes the loop opened by the sibling
## ``mixed/nim-uses-cpp-lib/`` fixture: that one routes Nim -> C; this
## one routes C++ -> Nim.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract IN THE REVERSE DIRECTION:
##
##   * TWO packages in a single ``repro.nim``: ``addlib`` (a Nim static
##     library, ``uses: nim``) and ``cppapp`` (a C++ executable,
##     ``uses: gcc``).
##   * ``depends_on cppapp: addlib`` — the C++ binary links against the
##     Nim archive. The cross-language dep cannot be detected by the
##     scanner (the C scanner only sees ``#include "cppapp/nim_addlib.h"``
##     which is a same-package include); the manual edge is the source
##     of truth.
##
## The Nim convention takes ownership of the WHOLE workspace because it's
## registered first AND ``addlib``'s ``uses:`` block names ``nim``. It
## then:
##   * Emits the Nim archive for ``addlib`` with ``--noMain`` so the
##     archive's ``main`` symbol does NOT collide with the C++ binary's
##     ``main()`` at link time. The archive contains both the
##     user-exported ``nimAdd`` symbol AND Nim's runtime-init ``NimMain``
##     entry point (the C++ binary calls ``NimMain()`` once before any
##     Nim function).
##   * Emits per-source ``g++ -c`` actions for ``cppapp/src/*.cpp`` plus
##     a terminal ``g++ -o cppapp.exe`` link action. The link action
##     picks up the Nim archive (``.repro/build/addlib/libaddlib.a``) as
##     a trailing positional + adds it to inputs + adds the archive
##     action's id to deps. Build sequencing strictly orders archive
##     before link.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     addlib/src/addlib.nim                  # Nim source (Layout B for Nim)
##     cppapp/src/main.cpp                    # C++ source (Layout B for C/C++)
##     cppapp/include/cppapp/nim_addlib.h     # hand-written C header
##
## NOTE on ``NimMain()``: the C++ source MUST call ``NimMain()`` once at
## startup before invoking any Nim function. The convention does NOT
## auto-insert this call — the user writes it explicitly in their C/C++
## code. This is the documented Nim FFI contract (see
## https://nim-lang.org/docs/nimc.html#dll-mode "Lib mode"); the
## convention simply ensures the symbol is exported from the archive
## (via ``--app:staticlib --noMain``).
##
## NOTE on header authorship: the user writes ``cppapp/include/cppapp/nim_addlib.h``
## BY HAND. Auto-generating C headers from Nim sources is out of scope for
## this milestone; the scanner extension that would extract ``{.exportc.}``
## declarations into a header is a future milestone.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package addlib:
  uses:
    "nim >=2.2 <3.0"

  library addlib

package cppapp:
  uses:
    "gcc >=11"

  executable cppapp:
    discard

# Manual dep edge: the C++ source's ``#include "cppapp/nim_addlib.h"``
# is a SAME-PACKAGE include (the header lives under cppapp/include/),
# so the C/C++ scanner produces no cross-package edge. The
# cross-language dep ``cppapp -> addlib`` is hand-authored here today;
# once the scanner gains an explicit cross-language-link pass (e.g.
# reading ``{.exportc.}`` declarations from the Nim sources), this
# edge moves into ``repro.scanned-deps.nim``.
depends_on cppapp: addlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# This file is empty today (the scanner cannot see the cross-language
# edge above) but the ``include`` is kept so the regeneration pipeline
# stays operative for future scanner extensions.
include "repro.scanned-deps.nim"
