# repro.scanned-deps.nim
#
# DO NOT EDIT — regenerated by `repro deps refresh`.
# Manual overrides belong in repro.nim.
#
# Engine version: 0.1.0
# Scanner schema: v1
# Targets scanned: 2 (1 with edges, 1 leaves)

# calc/src/main.ts:15: import { add } from "mathlib";
depends_on calcPkg: mathlibPkg

