## Mode 3 JavaScript/TypeScript pilot fixture — `binary-with-library`.
##
## Demonstrates the three-mode convention system's Mode 3 surface for
## JS/TS (curated `repro.nim` + auto-scanned dep graph) per
## `reprobuild-specs/Three-Mode-Convention-System.md` and the M33
## section of `reprobuild-specs/Mode3-Language-Expansion.milestones.org`:
##
##   * NO `package.json` / NO `tsconfig.json` / NO bundler config at
##     all — Mode 3 JS/TS is in-workspace only.
##   * Two packages declared in a single `repro.nim`:
##     `mathlibPkg` ships a library `mathlib` (a regular TypeScript
##     source tree exporting `add`); `calcPkg` ships an executable
##     `calc` whose `main.ts` imports the library.
##   * Per-package layout under the workspace root (Layout B-src in
##     `repro_core/jsts_dep_scanner`):
##       mathlib/src/index.ts
##       calc/src/main.ts
##   * The scanner reads `repro.scanned-deps.nim` (machine-authored
##     via `repro deps refresh`) at the bottom of this file and emits
##     the `calcPkg -> mathlibPkg` edge by recognising the
##     `import { add } from "mathlib";` line in `calc/src/main.ts`.
##
## The Mode 3 JS/TS convention (`jsts-direct`) turns the
## `depends_on calcPkg: mathlibPkg` edge into real action-graph edges:
## the convention emits one `esbuild --bundle` action per executable
## (consuming the library's sources directly via
## `--alias:mathlib=<libdir>/src/index.ts`) + an `fs.writeText` wrapper
## script action. The executable wrapper runs `node <bundle.js>` so
## the bundled JS produces the program's output.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlibPkg:
  uses:
    "typescript"

  library mathlib

package calcPkg:
  uses:
    "typescript"

  executable calc:
    discard

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# The scanner emits the `calcPkg -> mathlibPkg` edge (proved by
# `calc/src/main.ts`'s `import { add } from "mathlib";` line).
include "repro.scanned-deps.nim"
