## M44 Mode 3 Zig pilot fixture — pure Zig ``binary-with-library``.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" shape for
## Zig per the M44 section of
## ``reprobuild-specs/Mode3-Language-Expansion.milestones.org`` (the
## minimal subset the M44 ``zig-direct`` convention implements):
##
##   * NO ``build.zig`` at the workspace root (Mode 2 ``zig build``
##     delegation is deferred per the M44 honest-scope cut).
##   * Two packages declared in a single ``repro.nim``:
##     ``ziglibPkg`` ships a static library ``ziglib`` exposing an
##     ``export``-marked function; ``zigcalcPkg`` ships an executable
##     ``zigcalc`` whose source links the library archive.
##   * Per-package layout under the workspace root (Layout B):
##       ziglib/src/root.zig
##       zigcalc/src/main.zig
##
## The ``zig-direct`` convention turns the
## ``depends_on zigcalcPkg: ziglibPkg`` edge into real action-graph
## edges: ``zigcalc``'s ``zig build-exe -femit-bin=...`` link action
## declares ``ziglib``'s ``libziglib.a`` static archive as an explicit
## input AND as a trailing positional on the link argv, plus depends
## on the ``ziglib`` package's ``zig build-lib`` action id. Zig's
## ``build-exe`` driver forwards the archive to the underlying linker
## which resolves the cross-package symbol at link time.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package ziglibPkg:
  uses:
    "zig"

  library ziglib

package zigcalcPkg:
  uses:
    "zig"

  executable zigcalc:
    discard

# Manual dep edge: the M44 convention does not ship a Zig ``@import`` /
# ``extern`` scanner so cross-package edges are hand-authored. Once a
# future milestone lands the scanner this edge can move into
# ``repro.scanned-deps.nim``.
depends_on zigcalcPkg: ziglibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# Empty today (no Zig @import scanner) but the include is kept so the
# regeneration pipeline stays operative for future scanner extensions.
include "repro.scanned-deps.nim"
