## M59 Mode 3 Pascal pilot fixture — pure Pascal ``binary-with-library``.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" shape for
## Pascal per the M59 section of
## ``reprobuild-specs/Provisioning-And-Languages-Expansion.milestones.org``
## (the minimal subset the M59 ``pascal-direct`` convention implements):
##
##   * NO ``*.lpi`` at the workspace root (Mode 2 ``lazbuild`` delegation
##     is deferred per the M59 honest-scope cut).
##   * Two packages declared in a single ``repro.nim``:
##     ``pascallibPkg`` ships a static library ``pascallib`` exposing
##     a ``public name '...'; cdecl;``-marked function;
##     ``pascalcalcPkg`` ships an executable ``pascalcalc`` whose
##     source ``uses``-clauses the library and calls the exported
##     function.
##   * Per-package layout under the workspace root (Layout B)::
##       pascallib/src/lib.pas
##       pascalcalc/src/main.pas
##
## The ``pascal-direct`` convention turns the
## ``depends_on pascalcalcPkg: pascallibPkg`` edge into real
## action-graph edges: ``pascalcalc``'s ``fpc -O2 -o pascalcalc.exe
## main.pas`` action declares ``pascallib``'s ``libpascallib.a``
## static archive as an explicit input + trailing ``-k<archive>``
## (fpc linker pass-through), plus depends on the ``pascallib``
## package's ``ar rcs`` archive action. fpc's underlying linker
## resolves the cross-package symbol at link time.
##
## Build via::
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via::
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI::
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package pascallibPkg:
  uses:
    "fpc"

  library pascallib

package pascalcalcPkg:
  uses:
    "fpc"

  executable pascalcalc:
    discard

# Manual dep edge: the M59 convention does not ship a Pascal ``uses``
# clause scanner so cross-package edges are hand-authored. Once a
# future milestone lands the scanner this edge can move into
# ``repro.scanned-deps.nim``.
depends_on pascalcalcPkg: pascallibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# Empty today (no Pascal ``uses`` scanner) but the include is kept so
# the regeneration pipeline stays operative for future scanner
# extensions.
include "repro.scanned-deps.nim"
