## M59 cross-language pilot fixture (FORWARD direction) — a Pascal
## binary that calls into a C static library, declared together in a
## single workspace ``repro.nim``. Mirrors the Phase 4 cross-language
## schema for the Pascal↔C/C++ direction. The forward direction
## (Pascal → C) is one of two directions M59 ships; see the sibling
## ``mixed/cpp-uses-pascal-lib/`` fixture for the reverse case
## (C++ → Pascal).
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3"
## cross-language contract:
##
##   * TWO packages in a single ``repro.nim``: ``mathlib`` (a C static
##     library, ``uses: gcc``) and ``pascalcalc`` (a Pascal executable,
##     ``uses: fpc``).
##   * ``depends_on pascalcalcPkg: mathlibPkg`` — the Pascal binary's
##     link picks up the C archive. The cross-language dep cannot be
##     auto-detected by a Pascal source scanner (the scanner would see
##     ``external name 'c_add'`` which carries no upstream-package
##     reference); the manual edge is the source of truth.
##
## The pascal-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names a Pascal toolchain token and no ``*.lpi`` is present. It then:
##   * Emits per-source ``gcc -c`` actions for ``mathlib/src/*.c``
##     plus a terminal ``ar rcs libmathlib.a`` archive action, landing
##     the archive at ``.repro/build/mathlib/libmathlib.a``.
##   * Threads the archive on the ``fpc`` argv via ``-Fl<dir>`` (lib
##     search path) plus a trailing ``-k<archive>`` (linker
##     pass-through) so fpc's underlying linker resolves ``c_add`` at
##     link time.
##
## Layout::
##
##     repro.nim
##     repro.scanned-deps.nim
##     mathlib/src/add.c                     # C source (Layout B)
##     mathlib/include/mathlib/add.h         # public header
##     pascalcalc/src/main.pas               # Pascal source (Layout B)
##
## Build via::
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via::
##
##     repro deps refresh <this-dir>

import repro_project_dsl

package mathlibPkg:
  uses:
    "gcc >=11"

  library mathlib

package pascalcalcPkg:
  uses:
    "fpc"

  executable pascalcalc:
    discard

# Manual dep edge: the Pascal source's ``external name 'c_add'``
# declares the symbol but not the upstream package; the Pascal
# scanner cannot infer the cross-language link from that evidence.
# Hand-authored here today; once a scanner extension learns to fold
# ``external name`` declarations into the dep graph, this edge moves
# into ``repro.scanned-deps.nim``.
depends_on pascalcalcPkg: mathlibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
