## Mode 3 C/C++ pilot fixture — `binary-with-library`.
##
## Demonstrates the three-mode convention system's Mode 3 surface for
## C/C++ (curated `repro.nim` + auto-scanned dep graph) per
## `reprobuild-specs/Three-Mode-Convention-System.md` and the C/C++
## convention spec `reprobuild-specs/Language-Conventions/C-Cpp.md`:
##
##   * NO ecosystem manifest at all (no Makefile, no CMakeLists.txt, no
##     configure.ac).
##   * Two packages declared in a single `repro.nim`:
##     `mathlibPkg` ships a static library `mathlib`; `calcPkg` ships an
##     executable `calc` whose source `#include`s the library's public
##     header `mathlib/add.h`.
##   * Per-package layout under the workspace root:
##       mathlib/src/add.c
##       mathlib/include/mathlib/add.h
##       calc/src/calc.c
##     (Layout B in `repro_core/cpp_dep_scanner`.)
##   * The scanner reads `repro.scanned-deps.nim` (machine-authored via
##     `repro deps refresh`) at the bottom of this file and emits the
##     `mathlibPkg → calcPkg`-rejected, `calcPkg → mathlibPkg`-emitted
##     edge by recognising the `#include "mathlib/add.h"` line in
##     `calc/src/calc.c`.
##
## The C/C++ Mode 3 convention (`c_cpp_direct`) turns the
## `depends_on calcPkg: mathlibPkg` edge into real action-graph edges:
## `calc`'s `gcc -o calc.exe` link action declares `mathlib`'s
## `libmathlib.a` static archive as both an explicit input AND a
## positional argv token, and depends on the `mathlib` package's
## `ar rcs libmathlib.a` action id. Additionally, each upstream
## library's `include/` is threaded onto the downstream compile actions'
## `-I` flags so the executable's `#include "mathlib/add.h"` resolves at
## compile time.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlibPkg:
  uses:
    "gcc >=11"

  library mathlib

package calcPkg:
  uses:
    "gcc >=11"

  executable calc:
    discard

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# The scanner emits the `calcPkg -> mathlibPkg` edge (proved by
# `calc/src/calc.c`'s `#include "mathlib/add.h"` line).
include "repro.scanned-deps.nim"
