## M45 cross-language pilot fixture (FORWARD direction) — a D binary
## that calls into a C static library, declared together in a single
## workspace ``repro.nim``. Mirrors the Phase 4 cross-language schema
## for the D↔C/C++ direction. The forward direction (D → C) is one
## of two directions M45 ships; see the sibling
## ``mixed/cpp-uses-d-lib/`` fixture for the reverse case (C++ → D).
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract:
##
##   * TWO packages in a single ``repro.nim``: ``mathlib`` (a C static
##     library, ``uses: gcc``) and ``dcalc`` (a D executable,
##     ``uses: d``).
##   * ``depends_on dcalc: mathlib`` — the D binary's link picks up
##     the C archive. The cross-language dep cannot be auto-detected
##     by a D source scanner (the scanner would see ``extern (C)
##     c_add(...)`` which carries no upstream-package reference); the
##     manual edge is the source of truth.
##
## The d-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names a D toolchain token and no ``dub.json`` / ``dub.sdl`` is
## present. It then:
##   * Emits per-source ``gcc -c`` actions for ``mathlib/src/*.c``
##     plus a terminal ``ar rcs libmathlib.a`` archive action, landing
##     the archive at ``.repro/build/mathlib/libmathlib.a``.
##   * Threads the archive via ``-L=<archive>`` on the ``ldmd2`` argv
##     so D's underlying linker resolves ``c_add`` at link time.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     mathlib/src/add.c                     # C source (Layout B)
##     mathlib/include/mathlib/add.h         # public header
##     dcalc/src/main.d                      # D source (Layout B)
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlib:
  uses:
    "gcc >=11"

  library mathlib

package dcalc:
  uses:
    "d"

  executable dcalc:
    discard

# Manual dep edge: the D source's ``extern (C) c_add(...)`` declares
# the symbol but not the upstream package; the D scanner cannot
# infer the cross-language link from that evidence. Hand-authored
# here today; once a scanner extension learns to fold ``extern (C)``
# declarations into the dep graph, this edge moves into
# ``repro.scanned-deps.nim``.
depends_on dcalc: mathlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
