# repro.scanned-deps.nim
#
# DO NOT EDIT — regenerated by `repro deps refresh`.
# Manual overrides belong in repro.nim.
#
# Engine version: 0.1.0
# Scanner schema: v1
# Targets scanned: 1 (0 with edges, 1 leaves)

# (no inter-package dep edges discovered)
