## Mode 3 Nim pilot fixture.
##
## Demonstrates the three-mode convention system's Mode 3 surface
## (curated `repro.nim` + auto-scanned dep graph) per
## `reprobuild-specs/Three-Mode-Convention-System.md`:
##
##   * The canonical filename `repro.nim` (not `reprobuild.nim`); the
##     engine accepts both via the resolver in
##     `repro_core/project_file.nim`. Picking `repro.nim` here
##     dogfoods the alias.
##   * TWO packages in a single project file, each with one member:
##     `mode3PilotGreet` (a library) and `mode3PilotHello` (an
##     executable). The executable's source imports the library's
##     umbrella module, producing the expected inter-package edge
##     `mode3PilotHello -> mode3PilotGreet` in `repro.scanned-deps.nim`.
##   * The scanner reads `repro.scanned-deps.nim` (machine-authored
##     via `repro deps refresh`) at the bottom of this file.
##
## The Nim convention's engine-consumption pass turns the
## `depends_on mode3PilotHello: mode3PilotGreet` edge into a real
## action-graph edge: `hello`'s `gcc -o hello.exe` link action declares
## the greet package's `libgreet.a` static archive as both an explicit
## input AND a positional argv token, and depends on the greet
## package's `ar rcs libgreet.a` action id. The engine sequences the
## archive build strictly before the executable link.
##
## The two-package shape exercises the marker-collision fix landed in
## `libs/repro_project_dsl/src/repro_project_dsl/macros_a.nim`: prior
## to that fix, two `package` blocks sharing a project file caused a
## Nim "redefinition of reprobuildPackageMarker" compile error. The
## marker emission is now guarded by `when not declared(...)` so the
## second block is a no-op for marker purposes while still calling
## `registerPackageDef`.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mode3PilotGreet:
  uses:
    "nim >=2.2 <3.0"

  library greet

package mode3PilotHello:
  uses:
    "nim >=2.2 <3.0"

  executable hello:
    discard

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# The scanner emits the `mode3PilotHello -> mode3PilotGreet` edge
# (proved by `src/hello.nim`'s `import greet` line).
include "repro.scanned-deps.nim"
