## Mode 3 Nim pilot fixture.
##
## Demonstrates the three-mode convention system's Mode 3 surface
## (curated `repro.nim` + auto-scanned dep graph) per
## `reprobuild-specs/Three-Mode-Convention-System.md`:
##
##   * The canonical filename `repro.nim` (not `reprobuild.nim`); the
##     engine accepts both via the resolver in
##     `repro_core/project_file.nim`. Picking `repro.nim` here
##     dogfoods the alias.
##   * One package with two members: a library (`greet`) and an
##     executable (`hello`). The executable's source imports the
##     library's umbrella module.
##   * The scanner reads `repro.scanned-deps.nim` (machine-authored
##     via `repro deps refresh`) at the bottom of this file. Because
##     both members live in the SAME package, the scanner does not
##     emit a cross-package edge — the file's dep list is empty.
##     The file is still useful as the Mode 3 surface marker: it
##     proves the scanner ran, the file is byte-deterministic, and
##     the `--check` path returns 0 on CI.
##
## Multi-package fixtures (one workspace, two `package` declarations
## that import each other) are **deferred work**: today's DSL emits a
## `reprobuildPackageMarker` per package which collides when two
## packages share a project file. Gensym-per-package, or splitting the
## workspace into multiple project roots, lands with the workspace-
## scope follow-on milestone.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mode3Pilot:
  uses:
    "nim >=2.2 <3.0"

  library greet

  executable hello:
    discard

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# Today this file is essentially empty (both members above share the
# same package, so the scanner does not emit cross-package edges).
# Keeping the include line in place dogfoods the Mode 3 file-shape
# convention even when no edges are present.
include "repro.scanned-deps.nim"
