## M36 cross-language pilot fixture (REVERSE direction) — a C++ binary
## that calls into a Go static library, declared together in a single
## workspace ``repro.nim``. Closes the loop opened by the sibling
## ``mixed/go-uses-cpp-lib/`` fixture: that one routes Go -> C; this
## one routes C++ -> Go via Go's ``-buildmode=c-archive``.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-
## language contract in the REVERSE direction for Go:
##
##   * TWO packages in a single ``repro.nim``: ``goaddlib`` (a Go
##     static library, ``uses: go``) and ``cppapp`` (a C++ executable,
##     ``uses: gcc``).
##   * ``depends_on cppapp: goaddlib`` — the C++ binary's link picks
##     up the Go c-archive. The cross-language dep cannot be detected
##     by the scanner (the C++ scanner only sees the same-package
##     include of ``cppapp/goaddlib_wrapper.h``); the manual edge is
##     the source of truth.
##
## The go-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names ``go``. It then:
##   * Emits the Go library via ``go build -buildmode=c-archive`` (NOT
##     ``go tool compile -pack``) because ``goaddlib`` is marked
##     ``cConsumable=true`` (derived from the ``depends_on cppapp:
##     goaddlib`` edge: a C/C++ executable consumes the library, so it
##     needs C ABI, no Go-only metadata). The archive lands at
##     ``.repro/build/goaddlib/libgoaddlib.a`` and Go's c-archive
##     toolchain auto-emits a sibling ``libgoaddlib.h`` header in the
##     same directory.
##   * Emits per-source ``g++ -c`` actions for ``cppapp/src/*.cpp``
##     plus a terminal ``g++ -o cppapp.exe`` link action. The link argv
##     carries ``libgoaddlib.a`` as a trailing positional plus the
##     platform-specific Go runtime libs (Windows MinGW: ``-lws2_32
##     -lwinmm -lbcrypt -lntdll -luserenv -ladvapi32``; POSIX:
##     ``-lpthread -ldl -lm``). The archive's path lands on ``inputs``
##     + the archive action's id lands on ``deps``. Build sequencing
##     strictly orders archive before link.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     goaddlib/lib.go                              # Go source (Layout B)
##     cppapp/src/main.cpp                          # C++ source
##     cppapp/include/cppapp/goaddlib_wrapper.h     # hand-written C header
##
## NOTE on header authorship: Go's ``-buildmode=c-archive`` AUTO-emits
## a sibling ``libgoaddlib.h`` next to the ``.a`` archive carrying the
## C declarations for every ``//export``ed function. We provide a
## small hand-written wrapper header at
## ``cppapp/include/cppapp/goaddlib_wrapper.h`` that includes the
## generated header by absolute path — keeps the C++ source's include
## directives stable across build dirs.
##
## NOTE on Go runtime initialisation: unlike Nim (which requires a
## ``NimMain()`` call before any Nim function), Go's c-archive
## auto-initialises the Go runtime when ANY exported function is
## called — the cgo glue in the generated archive handles the
## ``_cgo_init`` dance transparently. The C++ source calls
## ``GoAdd(...)`` directly without an explicit initialiser.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package goaddlib:
  uses:
    "go"

  library goaddlib

package cppapp:
  uses:
    "gcc >=11"

  executable cppapp:
    discard

# Manual dep edge: the C++ source's ``#include "cppapp/goaddlib_wrapper.h"``
# is a SAME-PACKAGE include (the header lives under cppapp/include/),
# so the C/C++ scanner produces no cross-package edge. The
# cross-language dep ``cppapp -> goaddlib`` is hand-authored here today.
depends_on cppapp: goaddlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
