## M44 cross-language pilot fixture (REVERSE direction) — a C++ binary
## that calls into a Zig static library, declared together in a single
## workspace ``repro.nim``. Closes the loop opened by the sibling
## ``mixed/zig-uses-cpp-lib/`` fixture: that one routes Zig -> C; this
## one routes C++ -> Zig.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract in the REVERSE direction:
##
##   * TWO packages in a single ``repro.nim``: ``zigaddlib`` (a Zig
##     static library, ``uses: zig``) and ``cppapp`` (a C++ executable,
##     ``uses: gcc``).
##   * ``depends_on cppapp: zigaddlib`` — the C++ binary's link picks
##     up the Zig archive. The cross-language dep cannot be detected by
##     the scanner (the C++ scanner only sees a same-package include
##     of ``cppapp/zig_addlib.h``); the manual edge is the source of
##     truth.
##
## The zig-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names ``zig`` and no ``build.zig`` is present. It then:
##   * Emits the Zig library via ``zig build-lib`` landing at
##     ``.repro/build/zigaddlib/libzigaddlib.a`` — the canonical
##     archive schema shared with c-cpp-direct, Rust's staticlib path,
##     and Fortran's archive path.
##   * Emits per-source ``g++ -c`` actions for ``cppapp/src/*.cpp``
##     plus a terminal ``g++ -o cppapp.exe`` link action. The link
##     argv carries ``libzigaddlib.a`` as a trailing positional. Unlike
##     Rust/Fortran which need explicit ``-lpthread`` /
##     ``-lgfortran`` runtime libs, Zig static archives bundle the
##     (minimal) compiler-rt routines they need INTO the archive
##     itself, so the gcc/ld driver resolves the references against
##     the archive without external runtime libs.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     zigaddlib/src/root.zig                 # Zig source (Layout B)
##     cppapp/src/main.cpp                    # C++ source (Layout B)
##     cppapp/include/cppapp/zig_addlib.h     # hand-written C header
##
## NOTE on header authorship: the user writes
## ``cppapp/include/cppapp/zig_addlib.h`` BY HAND. Auto-generating C
## headers from Zig sources is out of scope for this milestone.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package zigaddlib:
  uses:
    "zig"

  library zigaddlib

package cppapp:
  uses:
    "gcc >=11"

  executable cppapp:
    discard

# Manual dep edge: the C++ source's ``#include "cppapp/zig_addlib.h"``
# is a SAME-PACKAGE include (the header lives under cppapp/include/),
# so the C/C++ scanner produces no cross-package edge. The
# cross-language dep ``cppapp -> zigaddlib`` is hand-authored here.
depends_on cppapp: zigaddlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
