# repro.scanned-deps.nim
#
# DO NOT EDIT — regenerated by `repro deps refresh`.
# Manual overrides belong in repro.nim.
#
# Engine version: 0.1.0
# Scanner schema: v1
# Targets scanned: 2 (1 with edges, 1 leaves)

# calc/calc/__main__.py:13: from mathlib import add
depends_on calcPkg: mathlibPkg

