## Mode 3 Python pilot fixture — `binary-with-library`.
##
## Demonstrates the three-mode convention system's Mode 3 surface for
## Python (curated `repro.nim` + auto-scanned dep graph) per
## `reprobuild-specs/Three-Mode-Convention-System.md` and the M32
## section of `reprobuild-specs/Mode3-Language-Expansion.milestones.org`:
##
##   * NO `pyproject.toml` / NO `setup.py` at all — Mode 3 Python is
##     in-workspace only.
##   * Two packages declared in a single `repro.nim`:
##     `mathlibPkg` ships a library `mathlib` (a regular Python package
##     directory with `__init__.py`); `calcPkg` ships an executable
##     `calc` whose `__main__.py` imports the library.
##   * Per-package layout under the workspace root (Layout B-flat in
##     `repro_core/python_dep_scanner`):
##       mathlib/mathlib/__init__.py
##       calc/calc/__init__.py
##       calc/calc/__main__.py
##   * The scanner reads `repro.scanned-deps.nim` (machine-authored
##     via `repro deps refresh`) at the bottom of this file and emits
##     the `calcPkg -> mathlibPkg` edge by recognising the
##     `from mathlib import add` line in `calc/calc/__main__.py`.
##
## The Mode 3 Python convention (`python-direct`) turns the
## `depends_on calcPkg: mathlibPkg` edge into real action-graph edges:
## the convention emits per-member `fs.preserveTree` (stage sources)
## + `python -m compileall` (byte-compile) + an `fs.writeText` wrapper
## script action. The executable wrapper's PYTHONPATH carries the
## mathlib staging dir so `from mathlib import add` resolves at runtime.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlibPkg:
  uses:
    "python3"

  library mathlib

package calcPkg:
  uses:
    "python3"

  executable calc:
    discard

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# The scanner emits the `calcPkg -> mathlibPkg` edge (proved by
# `calc/calc/__main__.py`'s `from mathlib import add` line).
include "repro.scanned-deps.nim"
