## Mode 3 cross-language pilot fixture — a Nim binary that calls into a
## C library, declared together in a single workspace ``repro.nim``.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract:
##
##   * TWO packages in a single ``repro.nim``: ``mathlib`` (a C static
##     library, ``uses: gcc``) and ``nimapp`` (a Nim executable,
##     ``uses: nim``).
##   * ``depends_on nimapp: mathlib`` is auto-emitted by the scanner from
##     ``src/nimapp.nim``'s ``{.importc, header: "mathlib/add.h".}``
##     declaration (the scanner picks up the ``#include`` evidence
##     indirectly via the ``header:`` argument once the C convention's
##     scanner observes the header reference; today the dep edge is
##     hand-authored in ``repro.scanned-deps.nim`` because the scanner's
##     ``importc``-header pass lands with a follow-on milestone).
##
## The Nim convention takes ownership of the WHOLE workspace because it's
## registered first and ``nimapp``'s ``uses:`` block names ``nim``. It then
## emits the C/C++ archive actions for ``mathlib`` in-line (per-source
## ``gcc -c`` + ``ar rcs libmathlib.a``) and wires them into ``nimapp``'s
## three-phase Nim build graph:
##
##   * Phase 1 (``nim c --compileOnly``) gains a ``--passC:-I<mathlib>/include``
##     flag so the C compiler invoked on the Nim-emitted ``.c`` files
##     resolves the user-written ``#include "mathlib/add.h"`` line.
##   * Phase 3 (``gcc -o nimapp.exe``) gains the ``libmathlib.a`` path as a
##     trailing positional + adds the archive to ``inputs`` + adds the
##     archive action's id to ``deps``. The engine sequences the archive
##     build strictly before the Nim link, and the linked executable
##     resolves ``add()`` against the C archive.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     src/nimapp.nim                        # Nim source (Layout A for Nim)
##     mathlib/src/add.c                     # C source (Layout B for C/C++)
##     mathlib/include/mathlib/add.h         # public header
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package mathlib:
  uses:
    "gcc >=11"

  library mathlib

package nimapp:
  uses:
    "nim >=2.2 <3.0"

  executable nimapp:
    discard

# Manual dep edge: the Nim source's ``{.importc, header: "mathlib/add.h".}``
# declaration is a cross-language dep that the Nim import-scanner does not
# yet pick up (the M3 Nim scanner extracts ``import foo`` lines only;
# folding ``{.importc.}``-header arguments into the dep graph is a follow-
# on milestone). Hand-authored here today; once the scanner gains that
# pass, this edge moves into ``repro.scanned-deps.nim`` and the include
# below picks it up.
depends_on nimapp: mathlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
# This file is empty today (the scanner cannot see the cross-language
# edge above) but the ``include`` is kept so the regeneration pipeline
# stays operative for future scanner extensions.
include "repro.scanned-deps.nim"
