## M34 cross-language pilot fixture (REVERSE direction) — a C++ binary
## that calls into a Rust static library, declared together in a single
## workspace ``repro.nim``. Closes the loop opened by the sibling
## ``mixed/rust-uses-cpp-lib/`` fixture: that one routes Rust -> C; this
## one routes C++ -> Rust.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-language
## contract in the REVERSE direction:
##
##   * TWO packages in a single ``repro.nim``: ``addlib`` (a Rust static
##     library, ``uses: rust``) and ``cppapp`` (a C++ executable,
##     ``uses: gcc``).
##   * ``depends_on cppapp: addlib`` — the C++ binary's link picks up
##     the Rust archive. The cross-language dep cannot be detected by
##     the scanner (the C++ scanner only sees a same-package include
##     of ``cppapp/rust_addlib.h``); the manual edge is the source of
##     truth.
##
## The rust-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names ``rust``. It then:
##   * Emits the Rust library as ``--crate-type=staticlib`` (NOT
##     ``rlib``) because ``addlib`` is marked ``cConsumable=true``
##     (derived from the ``depends_on cppapp: addlib`` edge: a C/C++
##     executable consumes the library, so it needs C ABI, no rlib
##     metadata). The archive lands at ``.repro/build/addlib/libaddlib.a``
##     — the canonical archive schema shared with c-cpp-direct and
##     the Nim convention.
##   * Emits per-source ``g++ -c`` actions for ``cppapp/src/*.cpp`` plus
##     a terminal ``g++ -o cppapp.exe`` link action. The link argv
##     carries ``libaddlib.a`` as a trailing positional plus the
##     platform-specific Rust runtime libs (Windows MinGW: ``-lws2_32
##     -luserenv -ladvapi32 -lbcrypt -lntdll``; POSIX: ``-lpthread -ldl
##     -lm``). The archive's path is added to ``inputs`` + the archive
##     action's id is added to ``deps``. Build sequencing strictly
##     orders archive before link.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     addlib/src/lib.rs                      # Rust source (Layout B)
##     cppapp/src/main.cpp                    # C++ source (Layout B)
##     cppapp/include/cppapp/rust_addlib.h    # hand-written C header
##
## NOTE on header authorship: the user writes
## ``cppapp/include/cppapp/rust_addlib.h`` BY HAND. Auto-generating C
## headers from Rust sources is out of scope for this milestone; the
## scanner extension that would extract ``#[no_mangle] pub extern "C"``
## declarations into a header is a future milestone.
##
## NOTE on Rust runtime initialisation: unlike Nim (which requires a
## ``NimMain()`` call before any Nim function), a Rust ``extern "C"``
## function with ``#[no_mangle]`` is directly callable from C/C++ — the
## Rust runtime initialiser (if any) is wired up automatically by the
## ``rustc`` static archive's link metadata. The C++ source can call
## ``rust_add`` directly without an explicit initialiser.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>
##
## Verify the scanned file is up-to-date in CI:
##
##     repro deps refresh --check <this-dir>

import repro_project_dsl

package addlib:
  uses:
    "rust"

  library addlib

package cppapp:
  uses:
    "gcc >=11"

  executable cppapp:
    discard

# Manual dep edge: the C++ source's ``#include "cppapp/rust_addlib.h"``
# is a SAME-PACKAGE include (the header lives under cppapp/include/),
# so the C/C++ scanner produces no cross-package edge. The
# cross-language dep ``cppapp -> addlib`` is hand-authored here today.
depends_on cppapp: addlib

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
