## M58 cross-language pilot fixture (REVERSE direction) — a C++
## binary that calls into an Ada static library, declared together in
## a single workspace ``repro.nim``. Closes the loop opened by the
## sibling ``mixed/ada-uses-cpp-lib/`` fixture: that one routes
## Ada → C; this one routes C++ → Ada.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-
## language contract in the REVERSE direction:
##
##   * TWO packages in a single ``repro.nim``: ``adaaddlib`` (an Ada
##     static library, ``uses: gnatmake``) and ``cppapp`` (a C++
##     executable, ``uses: gcc``).
##   * ``depends_on cppappPkg: adaaddlibPkg`` — the C++ binary's link
##     picks up the Ada archive. The cross-language dep cannot be
##     detected by the scanner (the C++ scanner only sees a same-
##     package include of ``cppapp/ada_addlib.h``); the manual edge
##     is the source of truth.
##
## The ada-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names an Ada toolchain token and no ``*.gpr`` is present. It then:
##   * Emits the Ada library via per-source ``gcc -c -gnatp`` + ``ar
##     rcs`` landing at ``.repro/build/adaaddlib/libadaaddlib.a`` —
##     the canonical archive schema shared with c-cpp-direct, Rust's
##     staticlib path, Fortran's archive path, Zig's static archive,
##     D's archive.
##   * Emits per-source ``g++ -c`` actions for ``cppapp/src/*.cpp``
##     plus a terminal ``g++ -o cppapp.exe`` link action. The link
##     argv carries ``libadaaddlib.a`` as a trailing positional.
##
##     The M58 honest-scope cut limits the reverse fixture to ``pragma
##     Export (C, ...)`` no-elaboration entry points so the gcc
##     driver resolves all references against the Ada archive itself
##     without external runtime libs — same property Zig's M44 / D's
##     M45 reverse fixtures rely on for their respective runtimes.
##     Full GNAT-runtime linking (``-lgnat -lm``) + ``adainit()`` /
##     ``adafinal()`` bracket calls + Ada tasking (``-lgnarl``) are
##     deferred to a future milestone.
##
## Layout:
##
##     repro.nim
##     repro.scanned-deps.nim
##     adaaddlib/src/lib.adb                    # Ada body (Layout B)
##     adaaddlib/src/lib.ads                    # Ada spec
##     cppapp/src/main.cpp                      # C++ source (Layout B)
##     cppapp/include/cppapp/ada_addlib.h       # hand-written C header
##
## NOTE on header authorship: the user writes
## ``cppapp/include/cppapp/ada_addlib.h`` BY HAND. Auto-generating C
## headers from Ada sources is out of scope for this milestone.
##
## Build via:
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via:
##
##     repro deps refresh <this-dir>

import repro_project_dsl

package adaaddlibPkg:
  uses:
    "gnatmake"

  library adaaddlib

package cppappPkg:
  uses:
    "gcc >=11"

  executable cppapp:
    discard

# Manual dep edge: the C++ source's ``#include "cppapp/ada_addlib.h"``
# is a SAME-PACKAGE include (the header lives under cppapp/include/),
# so the C/C++ scanner produces no cross-package edge. The
# cross-language dep ``cppappPkg -> adaaddlibPkg`` is hand-authored here.
depends_on cppappPkg: adaaddlibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
