## M59 cross-language pilot fixture (REVERSE direction) — a C++
## binary that calls into a Pascal static library, declared together in
## a single workspace ``repro.nim``. Closes the loop opened by the
## sibling ``mixed/pascal-uses-cpp-lib/`` fixture: that one routes
## Pascal → C; this one routes C++ → Pascal.
##
## Demonstrates the Three-Mode-Convention-System §"Mode 3" cross-
## language contract in the REVERSE direction:
##
##   * TWO packages in a single ``repro.nim``: ``pascaladdlib`` (a
##     Pascal static library, ``uses: fpc``) and ``cppapp`` (a C++
##     executable, ``uses: gcc``).
##   * ``depends_on cppappPkg: pascaladdlibPkg`` — the C++ binary's
##     link picks up the Pascal archive. The cross-language dep cannot
##     be detected by the scanner (the C++ scanner only sees a same-
##     package include of ``cppapp/pascal_addlib.h``); the manual edge
##     is the source of truth.
##
## The pascal-direct convention takes ownership of the WHOLE workspace
## because ``c-cpp-direct``'s recognize defers when ``uses:`` anywhere
## names a Pascal toolchain token and no ``*.lpi`` is present. It then:
##   * Emits the Pascal library via per-source ``fpc -O2 -CX`` + ``ar
##     rcs`` landing at ``.repro/build/pascaladdlib/libpascaladdlib.a``
##     — the canonical archive schema shared with c-cpp-direct, Rust's
##     staticlib path, Fortran's archive path, Zig's static archive,
##     D's archive, Ada's archive.
##   * Emits per-source ``g++ -c`` actions for ``cppapp/src/*.cpp``
##     plus a terminal ``g++ -o cppapp.exe`` link action. The link
##     argv carries ``libpascaladdlib.a`` as a trailing positional.
##
##     The M59 honest-scope cut limits the reverse fixture to
##     ``public name '...'; cdecl;`` no-RTL-bootstrap entry points so
##     the gcc driver resolves all references against the Pascal
##     archive itself without external runtime libs — same property
##     M58 Ada / M44 Zig / M45 D reverse fixtures rely on for their
##     respective runtimes. Full FPC-runtime linking
##     (``-lfprt -lc``) is deferred to a future milestone.
##
## Layout::
##
##     repro.nim
##     repro.scanned-deps.nim
##     pascaladdlib/src/lib.pas                 # Pascal unit (Layout B)
##     cppapp/src/main.cpp                      # C++ source (Layout B)
##     cppapp/include/cppapp/pascal_addlib.h    # hand-written C header
##
## NOTE on header authorship: the user writes
## ``cppapp/include/cppapp/pascal_addlib.h`` BY HAND. Auto-generating
## C headers from Pascal sources is out of scope for this milestone.
##
## Build via::
##
##     repro build <this-dir>#default --tool-provisioning=path
##
## Refresh the scanned deps via::
##
##     repro deps refresh <this-dir>

import repro_project_dsl

package pascaladdlibPkg:
  uses:
    "fpc"

  library pascaladdlib

package cppappPkg:
  uses:
    "gcc >=11"

  executable cppapp:
    discard

# Manual dep edge: the C++ source's ``#include "cppapp/pascal_addlib.h"``
# is a SAME-PACKAGE include (the header lives under cppapp/include/),
# so the C/C++ scanner produces no cross-package edge. The
# cross-language dep ``cppappPkg -> pascaladdlibPkg`` is hand-authored
# here.
depends_on cppappPkg: pascaladdlibPkg

# Workspace-internal dependencies, regenerated by `repro deps refresh`.
include "repro.scanned-deps.nim"
